server:
  port: 8084

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: stack-overflow
  auth-server-url: http://localhost:8080/auth
  resource: spring-boot
  public-client: true
  bearer-only: true